---
name: DNF CI
on: pull_request_target

jobs:
  copr-build:
    name: Copr Build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rpm-software-management/dnf-ci-host
    outputs:
      package-urls: ${{steps.copr-build.outputs.package-urls}}
    steps:
      - name: Check out ci-dnf-stack
        uses: actions/checkout@v2
        with:
          repository: rpm-software-management/ci-dnf-stack

      - name: Setup CI
        id: setup-ci
        uses: ./.github/actions/setup-ci
        with:
          copr-user: ${{secrets.COPR_USER}}
          copr-api-token: ${{secrets.COPR_API_TOKEN}}

      - name: Check out sources
        uses: actions/checkout@v2
        with:
          path: gits/${{github.event.pull_request.head.repo.name}}
          ref: ${{github.event.pull_request.head.sha}}  # check out the PR HEAD
          fetch-depth: 0

      - name: Run Copr Build
        id: copr-build
        uses: ./.github/actions/copr-build
        with:
          copr-user: ${{steps.setup-ci.outputs.copr-user}}
          overlay: createrepo_c-ci

  integration-tests:
    name: Integration Tests
    needs: copr-build
    runs-on: ubuntu-latest
    container:
      image: ghcr.io/rpm-software-management/dnf-ci-host
      options: --privileged
    steps:
      - name: Check out ci-dnf-stack
        uses: actions/checkout@v2
        with:
          repository: rpm-software-management/ci-dnf-stack

      - name: Run Integration Tests
        uses: ./.github/actions/integration-tests
        with:
          suite: createrepo_c
          package-urls: ${{needs.copr-build.outputs.package-urls}}

      - name: Publish Test Report
        if: always()
        uses: scacap/action-surefire-report@v1
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          report_paths: test-results/**/*.xml
            #
            #      - name: Publish test results
            #        uses: EnricoMi/publish-unit-test-result-action@v1
            #        if: always()
            #        with:
            #          files: test-results/**/*.xml
