---
name: Compile and run tests

on: [push, pull_request]

jobs:
  test-python-build:
    name: Test Python Build
    runs-on: ubuntu-latest
    container: fedora:latest
    steps:
      - uses: actions/checkout@v2

        #      - name: Install test dependencies
        #        run: |
        #          sudo dnf install -y python-pip
        #          sudo dnf install -y xz zchunk
        #
        #      - name: Install createrepo_c dependencies
        #        run: |
        #          sudo dnf install -y gcc make cmake bzip2-devel cairo-devel cairo-gobject-devel expat-devel file-devel glib2-devel gobject-introspection-devel libcurl-devel libmodulemd-devel libxml2-devel openssl-devel python3-devel rpm-devel sqlite-devel xz-devel zchunk-devel zlib-devel

      - name: Install dependencies
        run: |
          sudo dnf -y install dnf-plugins-core
          sudo dnf -y builddep createrepo_c.spec
          pip install pytest scikit-build

      - name: Compile
        run: python3 setup.py bdist_wheel

      - name: Install
        run: pip install dist/*.whl

      - name: Test
        run: pytest --verbose --color=yes tests/python/tests/
